BackendTest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render
from mealmngmt.views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('mealmngmt/', include('mealmngmt.urls', namespace="mealmngmt")),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

mealmngmt/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import MenuCreateView, MenuListView,  MenuRequestView, MenuDetailView

app_name = "mealmngmt"

urlpatterns = [
    path('create-menu/', login_required(MenuCreateView.as_view()), name='create-menu'),
    path('menu-list/', login_required(MenuListView.as_view()), name='menu-list'),
    path('menu-details/<pk>/',
         login_required(MenuDetailView.as_view()), name='menu-details'),
    path('menu/<pk>/', MenuRequestView.as_view(), name='menu')
]

mealmngmt/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser


# Actors
class User(AbstractUser):
    pass


class MealManager(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

# Entities


class Menu(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    message = models.CharField(max_length=140)
    date = models.DateField()
    mealmanager = models.ForeignKey(
        MealManager, on_delete=models.CASCADE, related_name='menus')

    def __str__(self):
        return str(self.id)


class MenuRequest(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    option = models.CharField(max_length=40)
    customization = models.CharField(max_length=140)
    menu = models.ForeignKey(
        Menu, on_delete=models.CASCADE, related_name='menurequests')

mealmngmt/forms.py
from django import forms
from django.conf import settings
from .models import Menu, MenuRequest


class CreateMenuModelForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = {
            'message',
            'date'
        }
        widgets = {
            'message': forms.Textarea,
            'date': forms.widgets.DateInput(attrs={'type': 'date'})
        }


class CreateMenuRequestModelForm(forms.ModelForm):
    class Meta:
        model = MenuRequest
        fields = {
            'first_name',
            'last_name',
            'option',
            'customization'
        }
        widgets = {
            'message': forms.Textarea,
            'date': forms.Textarea
        }


class SchedulerForm(forms.Form):
    initial_time = forms.IntegerField(initial=settings.OPEN_HOUR)
    final_time = forms.IntegerField(initial=settings.CLOSE_HOUR)
    interval = forms.IntegerField(initial=60)

mealmngmt/views.py
import datetime

from django.conf import settings
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views import generic
from .forms import CreateMenuModelForm, CreateMenuRequestModelForm, SchedulerForm
from .models import Menu, MealManager, MenuRequest

from scheduler.scheduler import scheduler, slack_reminder


class HomeView(generic.TemplateView):
    template_name = 'mealmngmt/home.html'


# Manager views

class MenuCreateView(generic.CreateView):
    template_name = 'mealmngmt/create_menu.html'
    form_class = CreateMenuModelForm
    uuid = ""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['msg'] = "Link para compartir el menu."
        context['detaillink'] = "{0}menu_details/{1}/".format(
            self.request.build_absolute_uri('/mealmngmt/'), self.uuid)
        context['sharelink'] = "{0}menu/{1}/".format(
            self.request.build_absolute_uri('/mealmngmt/'), self.uuid)
        context['uuid'] = self.uuid
        if self.uuid != "":
            context['post'] = True
        else:
            context['post'] = False

        return context

    def form_valid(self, form):
        menu = form.save(commit=False)
        menu.mealmanager = MealManager.objects.get(user=self.request.user)
        menu.save()
        self.uuid = menu
        context = self.get_context_data()

        scheduler.add_job(
            slack_reminder,
            args=[settings.OPEN_HOUR, settings.CLOSE_HOUR,
                  context['sharelink'], menu.id],
            trigger='interval',
            minutes=1,
            id="slack_reminder",
            max_instances=1,
            replace_existing=True,
        )

        return self.render_to_response(context)


class MenuListView(generic.ListView):
    template_name = "mealmngmt/menu_list.html"
    queryset = Menu.objects.all()


class MenuDetailView(generic.FormView):
    template_name = "mealmngmt/menu_details.html"
    form_class = SchedulerForm
    msg = ""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        menu = Menu.objects.get(id=self.kwargs['pk'])
        context["menu"] = menu
        context["requests"] = MenuRequest.objects.filter(menu=menu)
        context['msg'] = self.msg

        return context

    def form_valid(self, form):
        url = "{0}menu/{1}/".format(
            self.request.build_absolute_uri('/mealmngmt/'), self.kwargs['pk'])
        self.msg = "recordatorio actualizado"
        context = self.get_context_data()
        scheduler.add_job(
            slack_reminder,
            args=[form.cleaned_data['initial_time'],
                  form.cleaned_data['final_time'], url, self.kwargs['pk']],
            trigger='interval',
            minutes=form.cleaned_data['interval'],
            id="slack_reminder",
            max_instances=1,
            replace_existing=True,
        )
        return self.render_to_response(context)

# User View


class MenuRequestView(generic.CreateView):
    template_name = 'mealmngmt/menu.html'
    form_class = CreateMenuRequestModelForm
    msg = ""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        now = datetime.datetime.now()
        if settings.OPEN_HOUR <= now.hour < settings.CLOSE_HOUR:
            context['enabled'] = "enabled"
        else:
            context['enabled'] = "enabled"

        context['menu'] = Menu.objects.get(id=self.kwargs['pk']).message
        context['msg'] = self.msg

        return context

    def form_valid(self, form):
        menurequest = form.save(commit=False)
        menurequest.menu = Menu.objects.get(id=self.kwargs['pk'])
        menurequest.save()
        self.msg = "Solicitud enviada."
        context = self.get_context_data()

        return self.render_to_response(context)

mealmngmt/templates/mealmngmt/create_menu.html
{% extends "base.html" %}

{% block content %}

<div>
    <h1>Crear Menu del Día</h1>

    <form method="post" action".">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Publicar</button>
    </form>

    {% if post  %}

      {{msg}}    
      <p>
        Un recordatrio ha sido programado, para ver los pedidos y editar los recordatorios de slack dirigirse a:
        <a href = "{% url 'mealmngmt:menu-details' uuid %}">{{detaillink}}</a>
      </p>

      <p>
        Link del menu único para los usuarios:
        <a href = "{% url 'mealmngmt:menu' uuid %}">{{sharelink}}</a>
      </p>
      
    {% endif %}
</div>

{% endblock content %}

mealmngmt/templates/mealmngmt/home.html
{% extends "base.html" %} {% block content %}

<div>
	<h1>Landing Page</h1>
</div>

{% endblock content %}

mealmngmt/templates/mealmngmt/menu.html
{% extends "base.html" %} {% block content %}

<div>
	<h1>Menu del Día {{date}}</h1>

	{{ menu }}

	<form method="post" action"." >
      <fieldset {{enabled}}>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Solicitar</button>
      </fieldset>
    </form>

    {{msg}}    
      
</div>

{% endblock content %}

mealmngmt/templates/mealmngmt/menu_details.html
{% extends "base.html" %} {% block content %}
<script>jQuery(document).ready(function(){ jQuery('.timepicker').datepicker(); });</script>
<div>
	<h1>Menu del Día {{menu.date}}</h1>

	<p>{{menu.message}}</p>

	</h2>Editar recordatorio:</h2>
	<form method="post" action".">
      {% csrf_token %}
		{{form}}
		<button>Actualizar recordatorio</button>
		<p>{{msg}}
	</form>
	<h2>Lista de Pedidos</h2>

	<ul>
		{% for request in requests %}
		<li>
			{{request.first_name}} {{request.last_name}} {{request.option}}
			{{request.customization}}
		</li>
		{% endfor %}
	</ul>
    

</div>

{% endblock content %}

mealmngmt/templates/mealmngmt/menu_list.html
{% extends "base.html" %} {% block content %}

<div>
	<h1>Lista de Menus {{date}}</h1>
	<ul>
		{% for menu in object_list %}
		<li>{{menu.message}} {{menu.date}}</li>
		<a href="{% url 'mealmngmt:menu-details' menu.id %}">Detalles</a>
		{% endfor %}
	</ul>
</div>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CornerShop</title>
</head>
<body>
    <div>
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

templates/navbar.html
<header class="text-gray-700 body-font">
	<div
		class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center"
	>
		{% if request.user.is_authenticated %}
		<a href="{% url 'mealmngmt:create-menu' %}"> Crear Menu </a>
		<a href="{% url 'mealmngmt:menu-list' %}"> Lista de Menus </a>

		Logged in as: {{ request.user.username }}
		<a
			href="{% url 'logout' %}"
			class="ml-3 inline-flex items-center bg-gray-200 border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0"
		>
			Logout
		</a>
		{% else %}
		<a
			href="{% url 'login' %}"
			class="inline-flex items-center bg-gray-200 border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0"
		>
			Login
		</a>
		{% endif %}
	</div>
</header>